ALTER TABLE alerts
  DROP COLUMN IF EXISTS resolved_at,
  DROP COLUMN IF EXISTS fired_at,
  DROP COLUMN IF EXISTS threshold,
  DROP COLUMN IF EXISTS value,
  DROP COLUMN IF EXISTS metric,
  DROP COLUMN IF EXISTS rule;