ALTER TABLE alerts
  ADD COLUMN IF NOT EXISTS rule TEXT,
  ADD COLUMN IF NOT EXISTS metric TEXT,
  ADD COLUMN IF NOT EXISTS value DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS threshold DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS fired_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ;

UPDATE alerts
SET fired_at = created_at
WHERE fired_at IS NULL;

ALTER TABLE alerts
  ALTER COLUMN fired_at SET DEFAULT now();